"""Type stub for dlib — covers only the functions used by this project."""

from typing import Any, Sequence

import numpy as np


class rectangle:
    def width(self) -> int: ...
    def height(self) -> int: ...
    def left(self) -> int: ...
    def top(self) -> int: ...
    def right(self) -> int: ...
    def bottom(self) -> int: ...


class full_object_detection:
    def part(self, idx: int) -> point: ...
    @property
    def num_parts(self) -> int: ...


class point:
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...


class fhog_object_detector:
    def __call__(self, image: np.ndarray, upsample_num_times: int = ...) -> "rectangles": ...


class rectangles(Sequence[rectangle]):
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> rectangle: ...  # type: ignore[override]


class shape_predictor:
    def __init__(self, model_path: str) -> None: ...
    def __call__(self, image: np.ndarray, box: rectangle) -> full_object_detection: ...


def get_frontal_face_detector() -> fhog_object_detector: ...
